export const QUESTION_TITLES = [
  'Two Sum',
  'Add Two Numbers',
  'Longest Substring Without Repeating Characters',
  'Median of Two Sorted Arrays',
  'Longest Palindromic Substring',
  'Zigzag Conversion',
  'Reverse Integer',
  'String to Integer (atoi)',
  'Palindrome Number',
  'Regular Expression Matching',
  'Container With Most Water',
  'Integer to Roman',
  'Roman to Integer',
  'Longest Common Prefix',
  '3Sum',
  '3Sum Closest',
  'Letter Combinations of a Phone Number',
  '4Sum',
  'Valid Parentheses',
  'Generate Parentheses',
  'Remove Duplicates from Sorted Array',
  'Remove Element',
  'Implement strStr()',
  'Divide Two Integers',
  'Substring with Concatenation of All Words',
  'Next Permutation',
  'Longest Valid Parentheses',
  'Search in Rotated Sorted Array',
  'Find First and Last Position of Element in Sorted Array',
  'Search Insert Position',
  'Valid Sudoku',
  'Sudoku Solver',
  'Count and Say',
  'Combination Sum',
  'Combination Sum II',
  'First Missing Positive',
  'Trapping Rain Water',
  'Multiply Strings',
  'Wildcard Matching',
  'Jump Game II',
  'Permutations',
  'Permutations II',
  'Rotate Image',
  'Group Anagrams',
  'Pow(x, n)',
  'N-Queens',
  'Maximum Subarray',
  'Spiral Matrix',
  'Jump Game',
  'Merge Intervals',
  'Insert Interval',
  'Length of Last Word',
  'Spiral Matrix II',
  'Permutation Sequence',
  'Unique Paths',
  'Unique Paths II',
  'Minimum Path Sum',
  'Valid Number',
  'Plus One',
  'Add Binary',
  'Text Justification',
  'Sqrt(x)',
  'Climbing Stairs',
  'Simplify Path',
  'Edit Distance',
  'Set Matrix Zeroes',
  'Search a 2D Matrix',
  'Sort Colors',
  'Minimum Window Substring',
  'Subsets',
  'Word Search',
  'Remove Duplicates from Sorted Array II',
  'Search in Rotated Sorted Array II',
  'Largest Rectangle in Histogram',
  'Maximal Rectangle',
  'Scramble String',
  'Merge Sorted Array',
  'Gray Code',
  'Subsets II',
  'Decode Ways',
  'Restore IP Addresses',
  'Binary Tree Inorder Traversal',
  'Unique Binary Search Trees II',
  'Unique Binary Search Trees',
  'Interleaving String',
  'Validate Binary Search Tree',
  'Recover Binary Search Tree',
  'Same Tree',
  'Symmetric Tree',
  'Binary Tree Level Order Traversal',
  'Binary Tree Zigzag Level Order Traversal',
  'Maximum Depth of Binary Tree',
  'Construct Binary Tree from Preorder and Inorder Traversal',
  'Construct Binary Tree from Inorder and Postorder Traversal',
  'Binary Tree Level Order Traversal II',
  'Convert Sorted Array to Binary Search Tree',
  'Balanced Binary Tree',
  'Minimum Depth of Binary Tree',
  'Path Sum',
  'Path Sum II',
  'Flatten Binary Tree to Linked List',
  'Distinct Subsequences',
  'Populating Next Right Pointers in Each Node',
  'Populating Next Right Pointers in Each Node II',
  "Pascal's Triangle",
  "Pascal's Triangle II",
  'Triangle',
  'Best Time to Buy and Sell Stock',
  'Best Time to Buy and Sell Stock II',
  'Best Time to Buy and Sell Stock III',
  'Binary Tree Maximum Path Sum',
  'Valid Palindrome',
  'Word Ladder II',
  'Word Ladder',
  'Longest Consecutive Sequence',
  'Sum Root to Leaf Numbers',
  'Surrounded Regions',
  'Palindrome Partitioning',
  'Palindrome Partitioning II',
  'Clone Graph',
  'Gas Station',
  'Candy',
  'Single Number',
  'Single Number II',
  'Copy List with Random Pointer',
  'Word Break',
  'Word Break II',
  'Linked List Cycle',
  'Linked List Cycle II',
  'Binary Tree Preorder Traversal',
  'Binary Tree Postorder Traversal',
  'LRU Cache',
  'Insertion Sort List',
  'Sort List',
  'Max Points on a Line',
  'Evaluate Reverse Polish Notation',
  'Reverse Words in a String',
  'Maximum Product Subarray',
  'Find Minimum in Rotated Sorted Array',
  'Find Minimum in Rotated Sorted Array II',
  'Intersection of Two Linked Lists',
  'Find Peak Element',
  'Maximum Gap',
  'Compare Version Numbers',
  'Fraction to Recurring Decimal',
  'Two Sum II - Input Array Is Sorted',
  'Excel Sheet Column Title',
  'Majority Element',
  'Excel Sheet Column Number',
  'Factorial Trailing Zeroes',
  'Dungeon Game',
  'Largest Number',
  'Repeated DNA Sequences',
  'Best Time to Buy and Sell Stock IV',
  'Rotate Array',
  'House Robber',
  'Binary Tree Right Side View',
  'Number of Islands',
  'Happy Number',
  'Count Primes',
  'Isomorphic Strings',
  'Course Schedule',
  'Implement Trie (Prefix Tree)',
  'Minimum Size Subarray Sum',
  'Course Schedule II',
  'Design Add and Search Words Data Structure',
  'Word Search II',
  'House Robber II',
  'Shortest Palindrome',
  'Kth Largest Element in an Array',
  'Combination Sum III',
  'Contains Duplicate',
  'The Skyline Problem',
  'Contains Duplicate II',
  'Contains Duplicate III',
  'Maximal Square',
  'Count Complete Tree Nodes',
  'Rectangle Area',
  'Basic Calculator',
  'Invert Binary Tree',
  'Basic Calculator II',
  'Summary Ranges',
  'Majority Element II',
  'Kth Smallest Element in a BST',
  'Power of Two',
  'Number of Digit One',
  'Lowest Common Ancestor of a Binary Search Tree',
  'Lowest Common Ancestor of a Binary Tree',
  'Product of Array Except Self',
  'Sliding Window Maximum',
  'Search a 2D Matrix II',
  'Different Ways to Add Parentheses',
  'Valid Anagram',
  'Binary Tree Paths',
  'Add Digits',
  'Single Number III',
  'Ugly Number',
  'Ugly Number II',
  'Missing Number',
  'Integer to English Words',
  'H-Index',
  'H-Index II',
  'First Bad Version',
  'Perfect Squares',
  'Expression Add Operators',
  'Move Zeroes',
  'Peeking Iterator',
  'Find the Duplicate Number',
  'Game of Life',
  'Word Pattern',
  'Nim Game',
  'Find Median from Data Stream',
  'Serialize and Deserialize Binary Tree',
  'Bulls and Cows',
  'Longest Increasing Subsequence',
  'Remove Invalid Parentheses',
  'Range Sum Query - Immutable',
  'Range Sum Query 2D - Immutable',
  'Additive Number',
  'Range Sum Query - Mutable',
  'Best Time to Buy and Sell Stock with Cooldown',
  'Minimum Height Trees',
  'Burst Balloons',
  'Super Ugly Number',
  'Count of Smaller Numbers After Self',
  'Remove Duplicate Letters',
  'Maximum Product of Word Lengths',
  'Bulb Switcher',
  'Create Maximum Number',
  'Coin Change',
  'Wiggle Sort II',
  'Power of Three',
  'Count of Range Sum',
  'Longest Increasing Path in a Matrix',
  'Patching Array',
  'Verify Preorder Serialization of a Binary Tree',
  'Reconstruct Itinerary',
  'Increasing Triplet Subsequence',
  'Self Crossing',
  'Palindrome Pairs',
  'House Robber III',
  'Counting Bits',
  'Flatten Nested List Iterator',
  'Power of Four',
  'Integer Break',
  'Reverse String',
  'Reverse Vowels of a String',
  'Top K Frequent Elements',
  'Intersection of Two Arrays',
  'Intersection of Two Arrays II',
  'Data Stream as Disjoint Intervals',
  'Russian Doll Envelopes',
  'Design Twitter',
  'Count Numbers with Unique Digits',
  'Max Sum of Rectangle No Larger Than K',
  'Water and Jug Problem',
  'Valid Perfect Square',
  'Largest Divisible Subset',
  'Sum of Two Integers',
  'Super Pow',
  'Find K Pairs with Smallest Sums',
  'Guess Number Higher or Lower',
  'Guess Number Higher or Lower II',
  'Wiggle Subsequence',
  'Combination Sum IV',
  'Kth Smallest Element in a Sorted Matrix',
  'Insert Delete GetRandom O(1)',
  'Insert Delete GetRandom O(1) - Duplicates allowed',
  'Linked List Random Node',
  'Ransom Note',
  'Shuffle an Array',
  'Mini Parser',
  'Lexicographical Numbers',
  'First Unique Character in a String',
  'Longest Absolute File Path',
  'Find the Difference',
  'Elimination Game',
  'Perfect Rectangle',
  'Is Subsequence',
  'UTF-8 Validation',
  'Decode String',
  'Longest Substring with At Least K Repeating Characters',
  'Rotate Function',
  'Integer Replacement',
  'Random Pick Index',
  'Evaluate Division',
  'Nth Digit',
  'Remove K Digits',
  'Frog Jump',
  'Sum of Left Leaves',
  'Convert a Number to Hexadecimal',
  'Queue Reconstruction by Height',
  'Trapping Rain Water II',
  'Longest Palindrome',
  'Split Array Largest Sum',
  'Fizz Buzz',
  'Arithmetic Slices',
  'Third Maximum Number',
  'Add Strings',
  'Partition Equal Subset Sum',
  'Pacific Atlantic Water Flow',
  'Battleships in a Board',
  'Strong Password Checker',
  'Maximum XOR of Two Numbers in an Array',
  'Reconstruct Original Digits from English',
  'Longest Repeating Character Replacement',
  'All O`one Data Structure',
  'Minimum Genetic Mutation',
  'Number of Segments in a String',
  'Non-overlapping Intervals',
  'Find Right Interval',
  'Path Sum III',
  'Find All Anagrams in a String',
  'Arranging Coins',
  'Find All Duplicates in an Array',
  'String Compression',
  'Add Two Numbers II',
  'Arithmetic Slices II - Subsequence',
  'Number of Boomerangs',
  'Find All Numbers Disappeared in an Array',
  'Serialize and Deserialize BST',
  'Sort Characters By Frequency',
  'Minimum Number of Arrows to Burst Balloons',
  'Minimum Moves to Equal Array Elements',
  '4Sum II',
  'Assign Cookies',
  '132 Pattern',
  'Circular Array Loop',
  'Poor Pigs',
  'Repeated Substring Pattern',
  'LFU Cache',
  'Minimum Moves to Equal Array Elements II',
  'Island Perimeter',
  'Can I Win',
  'Count The Repetitions',
  'Unique Substrings in Wraparound String',
  'Validate IP Address',
  'Concatenated Words',
  'Matchsticks to Square',
  'Ones and Zeroes',
  'Heaters',
  'Total Hamming Distance',
  'Largest Palindrome Product',
  'Sliding Window Median',
  'Magical String',
  'License Key Formatting',
  'Smallest Good Base',
  'Max Consecutive Ones',
  'Predict the Winner',
  'Zuma Game',
  'Kth Smallest Instructions',
  'Increasing Subsequences',
  'Construct the Rectangle',
  'Reverse Pairs',
  'Target Sum',
  'Teemo Attacking',
  'Next Greater Element I',
  'Diagonal Traverse',
  'Keyboard Row',
  'Find Mode in Binary Search Tree',
  'IPO',
  'Next Greater Element II',
  'Base 7',
  'Relative Ranks',
  'Perfect Number',
  'Most Frequent Subtree Sum',
  'Find Bottom Left Tree Value',
  'Freedom Trail',
  'Find Largest Value in Each Tree Row',
  'Longest Palindromic Subsequence',
  'Super Washing Machines',
  'Coin Change 2',
  'Detect Capital',
  'Longest Uncommon Subsequence I',
  'Longest Uncommon Subsequence II',
  'Continuous Subarray Sum',
  'Longest Word in Dictionary through Deleting',
  'Contiguous Array',
  'Beautiful Arrangement',
  'Minesweeper',
  'Minimum Absolute Difference in BST',
  'K-diff Pairs in an Array',
  'Encode and Decode TinyURL',
  'Complex Number Multiplication',
  'Convert BST to Greater Tree',
  'Single Element in a Sorted Array',
  'Reverse String II',
  '01 Matrix',
  'Diameter of Binary Tree',
  'Remove Boxes',
  'Number of Provinces',
  'Student Attendance Record I',
  'Student Attendance Record II',
  'Optimal Division',
  'Brick Wall',
  'Next Greater Element III',
  'Reverse Words in a String III',
  'Subarray Sum Equals K',
  'Array Partition I',
  'Binary Tree Tilt',
  'Find the Closest Palindrome',
  'Array Nesting',
  'Reshape the Matrix',
  'Permutation in String',
  'Subtree of Another Tree',
  'Distribute Candies',
  'Out of Boundary Paths',
  'Shortest Unsorted Continuous Subarray',
  'Delete Operation for Two Strings',
  'Erect the Fence',
  'Tag Validator',
  'Fraction Addition and Subtraction',
  'Valid Square',
  'Longest Harmonious Subsequence',
  'Range Addition II',
  'Minimum Index Sum of Two Lists',
  'Non-negative Integers without Consecutive Ones',
  'Can Place Flowers',
  'Construct String from Binary Tree',
  'Find Duplicate File in System',
  'Valid Triangle Number',
  'Merge Two Binary Trees',
  'Task Scheduler',
  'Add One Row to Tree',
  'Maximum Product of Three Numbers',
  'K Inverse Pairs Array',
  'Course Schedule III',
  'Smallest Range Covering Elements from K Lists',
  'Sum of Square Numbers',
  'Exclusive Time of Functions',
  'Shopping Offers',
  'Decode Ways II',
  'Solve the Equation',
  'Maximum Average Subarray I',
  'Set Mismatch',
  'Maximum Length of Pair Chain',
  'Palindromic Substrings',
  'Replace Words',
  'Dota2 Senate',
  '2 Keys Keyboard',
  'Find Duplicate Subtrees',
  'Two Sum IV - Input is a BST',
  'Maximum Binary Tree',
  'Print Binary Tree',
  'Robot Return to Origin',
  'Find K Closest Elements',
  'Split Array into Consecutive Subsequences',
  'Image Smoother',
  'Maximum Width of Binary Tree',
  'Strange Printer',
  'Non-decreasing Array',
  'Beautiful Arrangement II',
  'Kth Smallest Number in Multiplication Table',
  'Trim a Binary Search Tree',
  'Maximum Swap',
  'Second Minimum Node In a Binary Tree',
  'Bulb Switcher II',
  'Number of Longest Increasing Subsequence',
  'Longest Continuous Increasing Subsequence',
  'Cut Off Trees for Golf Event',
  'Implement Magic Dictionary',
  'Map Sum Pairs',
  'Valid Parenthesis String',
  '24 Game',
  'Valid Palindrome II',
  'Baseball Game',
  'Redundant Connection',
  'Redundant Connection II',
  'Repeated String Match',
  'Longest Univalue Path',
  'Knight Probability in Chessboard',
  'Maximum Sum of 3 Non-Overlapping Subarrays',
  'Employee Importance',
  'Stickers to Spell Word',
  'Top K Frequent Words',
  'Max Area of Island',
  'Count Binary Substrings',
  'Degree of an Array',
  'Partition to K Equal Sum Subsets',
  'Falling Squares',
  'Minimum ASCII Delete Sum for Two Strings',
  'Subarray Product Less Than K',
  'Best Time to Buy and Sell Stock with Transaction Fee',
  '1-bit and 2-bit Characters',
  'Maximum Length of Repeated Subarray',
  'Find K-th Smallest Pair Distance',
  'Longest Word in Dictionary',
  'Accounts Merge',
  'Remove Comments',
  'Find Pivot Index',
  'Number of Atoms',
  'Self Dividing Numbers',
  'Count Different Palindromic Subsequences',
  'Flood Fill',
  'Asteroid Collision',
  'Parse Lisp Expression',
  'Monotone Increasing Digits',
  'Daily Temperatures',
  'Delete and Earn',
  'Cherry Pickup',
  'To Lower Case',
  'Network Delay Time',
  'Find Smallest Letter Greater Than Target',
  'Prefix and Suffix Search',
  'Min Cost Climbing Stairs',
  'Largest Number At Least Twice of Others',
  'Shortest Completing Word',
  'Contain Virus',
  'Open the Lock',
  'Cracking the Safe',
  'Reach a Number',
  'Pyramid Transition Matrix',
  'Set Intersection Size At Least Two',
  'Special Binary String',
  'N-ary Tree Level Order Traversal',
  'Flatten a Multilevel Doubly Linked List',
  'Prime Number of Set Bits in Binary Representation',
  'Partition Labels',
  'Largest Plus Sign',
  'Couples Holding Hands',
  'Construct Quad Tree',
  'Maximum Depth of N-ary Tree',
  'N-ary Tree Preorder Traversal',
  'N-ary Tree Postorder Traversal',
  'Toeplitz Matrix',
  'Reorganize String',
  'Max Chunks To Make Sorted II',
  'Max Chunks To Make Sorted',
  'Basic Calculator IV',
  'Jewels and Stones',
  'Sliding Puzzle',
  'Global and Local Inversions',
  'Binary Search',
  'Swap Adjacent in LR String',
  'Swim in Rising Water',
  'K-th Symbol in Grammar',
  'Reaching Points',
  'Rabbits in Forest',
  'Transform to Chessboard',
  'Minimum Distance Between BST Nodes',
  'Letter Case Permutation',
  'Is Graph Bipartite?',
  'K-th Smallest Prime Fraction',
  'Cheapest Flights Within K Stops',
  'Rotated Digits',
  'Escape The Ghosts',
  'Domino and Tromino Tiling',
  'Custom Sort String',
  'Number of Matching Subsequences',
  'Preimage Size of Factorial Zeroes Function',
  'Valid Tic-Tac-Toe State',
  'Number of Subarrays with Bounded Maximum',
  'Rotate String',
  'All Paths From Source to Target',
  'Smallest Rotation with Highest Score',
  'Champagne Tower',
  'Design HashSet',
  'Design HashMap',
  'Minimum Swaps To Make Sequences Increasing',
  'Find Eventual Safe States',
  'Bricks Falling When Hit',
  'Unique Morse Code Words',
  'Split Array With Same Average',
  'Number of Lines To Write String',
  'Max Increase to Keep City Skyline',
  'Soup Servings',
  'Expressive Words',
  'Chalkboard XOR Game',
  'Subdomain Visit Count',
  'Largest Triangle Area',
  'Largest Sum of Averages',
  'Binary Tree Pruning',
  'Bus Routes',
  'Ambiguous Coordinates',
  'Linked List Components',
  'Race Car',
  'Most Common Word',
  'Short Encoding of Words',
  'Shortest Distance to a Character',
  'Card Flipping Game',
  'Binary Trees With Factors',
  'Goat Latin',
  'Friends Of Appropriate Ages',
  'Most Profit Assigning Work',
  'Making A Large Island',
  'Count Unique Characters of All Substrings of a Given String',
  'Consecutive Numbers Sum',
  'Positions of Large Groups',
  'Masking Personal Information',
  'Design Circular Deque',
  'Design Circular Queue',
  'Flipping an Image',
  'Find And Replace in String',
  'Sum of Distances in Tree',
  'Image Overlap',
  'Rectangle Overlap',
  'New 21 Game',
  'Push Dominoes',
  'Similar String Groups',
  'Magic Squares In Grid',
  'Keys and Rooms',
  'Split Array into Fibonacci Sequence',
  'Guess the Word',
  'Backspace String Compare',
  'Longest Mountain in Array',
  'Hand of Straights',
  'Shortest Path Visiting All Nodes',
  'Shifting Letters',
  'Maximize Distance to Closest Person',
  'Rectangle Area II',
  'Loud and Rich',
  'Peak Index in a Mountain Array',
  'Car Fleet',
  'K-Similar Strings',
  'Score of Parentheses',
  'Minimum Cost to Hire K Workers',
  'Mirror Reflection',
  'Buddy Strings',
  'Lemonade Change',
  'Score After Flipping Matrix',
  'Shortest Subarray with Sum at Least K',
  'All Nodes Distance K in Binary Tree',
  'Random Pick with Blacklist',
  'Shortest Path to Get All Keys',
  'Smallest Subtree with all the Deepest Nodes',
  'Prime Palindrome',
  'Transpose Matrix',
  'Binary Gap',
  'Reordered Power of 2',
  'Advantage Shuffle',
  'Minimum Number of Refueling Stops',
  'Implement Rand10() Using Rand7()',
  'Leaf-Similar Trees',
  'Length of Longest Fibonacci Subsequence',
  'Walking Robot Simulation',
  'Koko Eating Bananas',
  'Stone Game',
  'Nth Magical Number',
  'Profitable Schemes',
  'Random Pick with Weight',
  'Random Flip Matrix',
  'Random Point in Non-overlapping Rectangles',
  'Generate Random Point in a Circle',
  'Decoded String at Index',
  'Boats to Save People',
  'Projection Area of 3D Shapes',
  'Uncommon Words from Two Sentences',
  'Spiral Matrix III',
  'Possible Bipartition',
  'Super Egg Drop',
  'Fair Candy Swap',
  'Construct Binary Tree from Preorder and Postorder Traversal',
  'Find and Replace Pattern',
  'Sum of Subsequence Widths',
  'Surface Area of 3D Shapes',
  'Groups of Special-Equivalent Strings',
  'All Possible Full Binary Trees',
  'Maximum Frequency Stack',
  'Monotonic Array',
  'Increasing Order Search Tree',
  'Bitwise ORs of Subarrays',
  'Orderly Queue',
  'RLE Iterator',
  'Numbers At Most N Given Digit Set',
  'Valid Permutations for DI Sequence',
  'Fruit Into Baskets',
  'Sort Array By Parity',
  'Super Palindromes',
  'Sum of Subarray Minimums',
  'Smallest Range I',
  'Snakes and Ladders',
  'Smallest Range II',
  'Online Election',
  'Sort an Array',
  'Cat and Mouse',
  'X of a Kind in a Deck of Cards',
  'Partition Array into Disjoint Intervals',
  'Word Subsets',
  'Reverse Only Letters',
  'Maximum Sum Circular Subarray',
  'Complete Binary Tree Inserter',
  'Number of Music Playlists',
  'Minimum Add to Make Parentheses Valid',
  'Sort Array By Parity II',
  '3Sum With Multiplicity',
  'Minimize Malware Spread',
  'Long Pressed Name',
  'Flip String to Monotone Increasing',
  'Three Equal Parts',
  'Minimize Malware Spread II',
  'Unique Email Addresses',
  'Binary Subarrays With Sum',
  'Minimum Falling Path Sum',
  'Beautiful Array',
  'Shortest Bridge',
  'Knight Dialer',
  'Stamping The Sequence',
  'Reorder Data in Log Files',
  'Range Sum of BST',
  'Minimum Area Rectangle',
  'Distinct Subsequences II',
  'Valid Mountain Array',
  'DI String Match',
  'Find the Shortest Superstring',
  'Delete Columns to Make Sorted',
  'Minimum Increment to Make Array Unique',
  'Validate Stack Sequences',
  'Most Stones Removed with Same Row or Column',
  'Bag of Tokens',
  'Largest Time for Given Digits',
  'Reveal Cards In Increasing Order',
  'Flip Equivalent Binary Trees',
  'Largest Component Size by Common Factor',
  'Verifying an Alien Dictionary',
  'Array of Doubled Pairs',
  'Delete Columns to Make Sorted II',
  'Tallest Billboard',
  'Prison Cells After N Days',
  'Check Completeness of a Binary Tree',
  'Regions Cut By Slashes',
  'Delete Columns to Make Sorted III',
  'N-Repeated Element in Size 2N Array',
  'Maximum Width Ramp',
  'Minimum Area Rectangle II',
  'Least Operators to Express Number',
  'Univalued Binary Tree',
  'Vowel Spellchecker',
  'Numbers With Same Consecutive Differences',
  'Binary Tree Cameras',
  'Pancake Sorting',
  'Powerful Integers',
  'Flip Binary Tree To Match Preorder Traversal',
  'Equal Rational Numbers',
  'Fibonacci Number',
  'K Closest Points to Origin',
  'Subarray Sums Divisible by K',
  'Odd Even Jump',
  'Largest Perimeter Triangle',
  'Squares of a Sorted Array',
  'Longest Turbulent Subarray',
  'Distribute Coins in Binary Tree',
  'Unique Paths III',
  'Time Based Key-Value Store',
  'Triples with Bitwise AND Equal To Zero',
  'Minimum Cost For Tickets',
  'String Without AAA or BBB',
  'Sum of Even Numbers After Queries',
  'Interval List Intersections',
  'Vertical Order Traversal of a Binary Tree',
  'Smallest String Starting From Leaf',
  'Add to Array-Form of Integer',
  'Satisfiability of Equality Equations',
  'Broken Calculator',
  'Subarrays with K Different Integers',
  'Cousins in Binary Tree',
  'Rotting Oranges',
  'Minimum Number of K Consecutive Bit Flips',
  'Number of Squareful Arrays',
  'Find the Town Judge',
  'Available Captures for Rook',
  'Minimum Cost to Merge Stones',
  'Grid Illumination',
  'Find Common Characters',
  'Check If Word Is Valid After Substitutions',
  'Max Consecutive Ones III',
  'Maximize Sum Of Array After K Negations',
  'Clumsy Factorial',
  'Minimum Domino Rotations For Equal Row',
  'Construct Binary Search Tree from Preorder Traversal',
  'Pairs of Songs With Total Durations Divisible by 60',
  'Capacity To Ship Packages Within D Days',
  'Numbers With Repeated Digits',
  'Partition Array Into Three Parts With Equal Sum',
  'Best Sightseeing Pair',
  'Smallest Integer Divisible by K',
  'Binary String With Substrings Representing 1 To N',
  'Convert to Base -2',
  'Binary Prefix Divisible By 5',
  'Next Greater Node In Linked List',
  'Number of Enclaves',
  'Remove Outermost Parentheses',
  'Sum of Root To Leaf Binary Numbers',
  'Camelcase Matching',
  'Video Stitching',
  'Divisor Game',
  'Longest Arithmetic Subsequence',
  'Maximum Difference Between Node and Ancestor',
  'Recover a Tree From Preorder Traversal',
  'Matrix Cells in Distance Order',
  'Two City Scheduling',
  'Maximum Sum of Two Non-Overlapping Subarrays',
  'Stream of Characters',
  'Moving Stones Until Consecutive',
  'Coloring A Border',
  'Uncrossed Lines',
  'Escape a Large Maze',
  'Minimum Score Triangulation of Polygon',
  'Find Words That Can Be Formed by Characters',
  'Moving Stones Until Consecutive II',
  'Binary Search Tree to Greater Sum Tree',
  'Valid Boomerang',
  'Maximum Level Sum of a Binary Tree',
  'As Far from Land as Possible',
  'Robot Bounded In Circle',
  'Flower Planting With No Adjacent',
  'Partition Array for Maximum Sum',
  'Longest Duplicate Substring',
  'Last Stone Weight',
  'Remove All Adjacent Duplicates In String',
  'Longest String Chain',
  'Last Stone Weight II',
  'Last Substring in Lexicographical Order',
  'Height Checker',
  'Grumpy Bookstore Owner',
  'Previous Permutation With One Swap',
  'Distant Barcodes',
  'Number of Submatrices That Sum to Target',
  'Greatest Common Divisor of Strings',
  'Flip Columns For Maximum Number of Equal Rows',
  'Adding Two Negabinary Numbers',
  'Occurrences After Bigram',
  'Insufficient Nodes in Root to Leaf Paths',
  'Smallest Subsequence of Distinct Characters',
  'Letter Tile Possibilities',
  'Duplicate Zeros',
  'Largest Values From Labels',
  'Shortest Common Supersequence ',
  'Shortest Path in Binary Matrix',
  'Statistics from a Large Sample',
  'Car Pooling',
  'Find in Mountain Array',
  'Brace Expansion II',
  'Path In Zigzag Labelled Binary Tree',
  'Distribute Candies to People',
  'Filling Bookcase Shelves',
  'Parsing A Boolean Expression',
  'Defanging an IP Address',
  'Corporate Flight Bookings',
  'Delete Nodes And Return Forest',
  'Maximum Nesting Depth of Two Valid Parentheses Strings',
  'Mean of Array After Removing Some Elements',
  'Iterator for Combination',
  'Relative Sort Array',
  'Lowest Common Ancestor of Deepest Leaves',
  'Longest Well-Performing Interval',
  'Smallest Sufficient Team',
  'Element Appearing More Than 25% In Sorted Array',
  'Remove Covered Intervals',
  'Graph Connectivity With Threshold',
  'Minimum Falling Path Sum II',
  'Number of Equivalent Domino Pairs',
  'Minimum Cost Tree From Leaf Values',
  'Shortest Path with Alternating Colors',
  'Maximum of Absolute Value Expression',
  'Replace Elements with Greatest Element on Right Side',
  'Sum of Mutated Array Closest to Target',
  'Number of Paths with Max Score',
  'N-th Tribonacci Number',
  'Alphabet Board Path',
  'Largest 1-Bordered Square',
  'Stone Game II',
  'Decompress Run-Length Encoded List',
  'Matrix Block Sum',
  'Sum of Nodes with Even-Valued Grandparent',
  'Distinct Echo Substrings',
  'Decrease Elements To Make Array Zigzag',
  'Binary Tree Coloring Game',
  'Snapshot Array',
  'Longest Common Subsequence',
  'Longest Chunked Palindrome Decomposition',
  'Break a Palindrome',
  'Sort the Matrix Diagonally',
  'Reverse Subarray To Maximize Array Value',
  'Rank Transform of an Array',
  'Rank Transform of a Matrix',
  'Day of the Year',
  'Swap For Longest Repeated Character Substring',
  'Online Majority Element In Subarray',
  'Number of Dice Rolls With Target Sum',
  'Maximum Number of Words You Can Type',
  'Remove Zero Sum Consecutive Nodes from Linked List',
  'Dinner Plate Stacks',
  'Invalid Transactions',
  'Compare Strings by Frequency of the Smallest Character',
  'Number of Days Between Two Dates',
  'Validate Binary Tree Nodes',
  'Closest Divisors',
  'Largest Multiple of Three',
  'Prime Arrangements',
  'Can Make Palindrome from Substring',
  'Reformat Date',
  'Four Divisors',
  'Balance a Binary Search Tree',
  'Constrained Subsequence Sum',
  'Distance Between Bus Stops',
  'Maximum Subarray Sum with One Deletion',
  'Day of the Week',
  'Make Array Strictly Increasing',
  'Range Frequency Queries',
  'Minimum Garden Perimeter to Collect Enough Apples',
  'Kth Ancestor of a Tree Node',
  'Maximum Number of Balloons',
  'Reverse Substrings Between Each Pair of Parentheses',
  'K-Concatenation Maximum Sum',
  'Critical Connections in a Network',
  'Delete Characters to Make Fancy String',
  'Minimum Moves to Reach Target Score',
  'Longest Happy String',
  'Number of Visible People in a Queue',
  'Minimum Absolute Difference',
  'Ugly Number III',
  'Smallest String With Swaps',
  'Sort Items by Groups Respecting Dependencies',
  'Watering Plants',
  'Largest Magic Square',
  'Count Artifacts That Can Be Extracted',
  'Count Ways to Build Rooms in an Ant Colony',
  'Unique Number of Occurrences',
  'Remove All Adjacent Duplicates in String II',
  'Get Equal Substrings Within Budget',
  'Minimum Moves to Reach Target with Rotations',
  'Where Will the Ball Fall',
  'Sum of Floored Pairs',
  'Minimum Cost to Move Chips to The Same Position',
  'Longest Arithmetic Subsequence of Given Difference',
  'Path with Maximum Gold',
  'Count Vowels Permutation',
  'Sort the Jumbled Numbers',
  'Maximum Candies Allocated to K Children',
  'Maximum Product of the Length of Two Palindromic Substrings',
  'Split a String in Balanced Strings',
  'Queens That Can Attack the King',
  'Dice Roll Simulation',
  'Maximum Equal Frequency',
  'Maximize the Topmost Element After K Moves',
  'Check If It Is a Straight Line',
  'Remove Sub-Folders from the Filesystem',
  'Replace the Substring for Balanced String',
  'Maximum Profit in Job Scheduling',
  'Find Players With Zero or One Losses',
  'Minimum Deletions to Make Array Beautiful',
  'Minimum Number of Moves to Make Palindrome',
  'Find Positive Integer Solution for a Given Equation',
  'Circular Permutation in Binary Representation',
  'Maximum Length of a Concatenated String with Unique Characters',
  'Tiling a Rectangle with the Fewest Squares',
  'Airplane Seat Assignment Probability',
  'Tuple with Same Product',
  'Maximum Height by Stacking Cuboids ',
  'Minimum Swaps to Make Strings Equal',
  'Count Number of Nice Subarrays',
  'Minimum Remove to Make Valid Parentheses',
  'Check If It Is a Good Array',
  'Find Palindrome With Fixed Length',
  'Cells with Odd Values in a Matrix',
  'Reconstruct a 2-Row Binary Matrix',
  'Number of Closed Islands',
  'Maximum Score Words Formed by Letters',
  'Shift 2D Grid',
  'Find Elements in a Contaminated Binary Tree',
  'Greatest Sum Divisible by Three',
  'Minimum Moves to Move a Box to Their Target Location',
  'Find the Difference of Two Arrays',
  'Maximum Value of K Coins From Piles',
  'Minimum Time Visiting All Points',
  'Count Servers that Communicate',
  'Search Suggestions System',
  'Number of Ways to Stay in the Same Place After Some Steps',
  'Find Winner on a Tic Tac Toe Game',
  'Number of Burgers with No Waste of Ingredients',
  'Count Square Submatrices with All Ones',
  'Palindrome Partitioning III',
  'Group the People Given the Group Size They Belong To',
  'Find the Smallest Divisor Given a Threshold',
  'Minimum Number of Flips to Convert Binary Matrix to Zero Matrix',
  'Convert Binary Number in a Linked List to Integer',
  'Maximum Side Length of a Square with Sum Less than or Equal to Threshold',
  'Shortest Path in a Grid with Obstacles Elimination',
  'Find Numbers with Even Number of Digits',
  'Divide Array in Sets of K Consecutive Numbers',
  'Maximum Number of Occurrences of a Substring',
  'Maximum Candies You Can Get from Boxes',
  'Find N Unique Integers Sum up to Zero',
  'All Elements in Two Binary Search Trees',
  'Jump Game III',
  'Verbal Arithmetic Puzzle',
  'All Ancestors of a Node in a Directed Acyclic Graph',
  'Encrypt and Decrypt Strings',
  'Decrypt String from Alphabet to Integer Mapping',
  'XOR Queries of a Subarray',
  'Get Watched Videos by Your Friends',
  'Minimum Insertion Steps to Make a String Palindrome',
  'Convert Integer to the Sum of Two No-Zero Integers',
  'Number of Operations to Make Network Connected',
  'Minimum Distance to Type a Word Using Two Fingers',
  'Number of Steps to Reduce a Number to Zero',
  'Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold',
  'Angle Between Hands of a Clock',
  'Jump Game IV',
  'Maximum 69 Number',
  'Print Words Vertically',
  'Delete Leaves With a Given Value',
  'Minimum Number of Taps to Open to Water a Garden',
  'Remove Palindromic Subsequences',
  'Filter Restaurants by Vegan-Friendly, Price and Distance',
  'Find the City With the Smallest Number of Neighbors at a Threshold Distance',
  'Minimum Difficulty of a Job Schedule',
  'Sort Integers by The Number of 1 Bits',
  'Apply Discount Every n Orders',
  'Number of Substrings Containing All Three Characters',
  'Count All Valid Pickup and Delivery Options',
  'The K Weakest Rows in a Matrix',
  'Reduce Array Size to The Half',
  'Maximum Product of Splitted Binary Tree',
  'Jump Game V',
  'Check If N and Its Double Exist',
  'Minimum Number of Steps to Make Two Strings Anagram',
  'Tweet Counts Per Frequency',
  'Maximum Students Taking Exam',
  'Increasing Decreasing String',
  'Find the Longest Substring Containing Vowels in Even Counts',
  'Longest ZigZag Path in a Binary Tree',
  'Maximum Sum BST in Binary Tree',
  'Count Negative Numbers in a Sorted Matrix',
  'Product of the Last K Numbers',
  'Maximum Number of Events That Can Be Attended',
  'Construct Target Array With Multiple Sums',
  'How Many Numbers Are Smaller Than the Current Number',
  'Rank Teams by Votes',
  'Linked List in Binary Tree',
  'Minimum Cost to Make at Least One Valid Path in a Grid',
  'Find the Distance Value Between Two Arrays',
  'Cinema Seat Allocation',
  'Sort Integers by The Power Value',
  'Pizza With 3n Slices',
  'Generate a String With Characters That Have Odd Counts',
  'Number of Times Binary String Is Prefix-Aligned',
  'Time Needed to Inform All Employees',
  'Frog Position After T Seconds',
  'Lucky Numbers in a Matrix',
  'Design a Stack With Increment Operation',
  'Find a Corresponding Node of a Binary Tree in a Clone of That Tree',
  'Maximum Performance of a Team',
  'Count Largest Group',
  'Circle and Rectangle Overlapping',
  'Construct K Palindrome Strings',
  'Reducing Dishes',
  'Create Target Array in the Given Order',
  'Check if There is a Valid Path in a Grid',
  'Longest Happy Prefix',
  'Find Lucky Integer in an Array',
  'Count Number of Teams',
  'Design Underground System',
  'Find All Good Strings',
  'Minimum Value to Get Positive Step by Step Sum',
  'Find the Minimum Number of Fibonacci Numbers Whose Sum Is K',
  'The k-th Lexicographical String of All Happy Strings of Length n',
  'Restore The Array',
  'Minimum Subsequence in Non-Increasing Order',
  'Number of Steps to Reduce a Number in Binary Representation to One',
  'Stone Game III',
  'String Matching in an Array',
  'Queries on a Permutation With Key',
  'HTML Entity Parser',
  'Number of Ways to Paint N × 3 Grid',
  'Kids With the Greatest Number of Candies',
  'Max Difference You Can Get From Changing an Integer',
  'Check If a String Can Break Another String',
  'Number of Ways to Wear Different Hats to Each Other',
  'Reformat The String',
  'Display Table of Food Orders in a Restaurant',
  'Minimum Number of Frogs Croaking',
  'Build Array Where You Can Find The Maximum Exactly K Comparisons',
  'Maximum Score After Splitting a String',
  'Maximum Points You Can Obtain from Cards',
  'Diagonal Traverse II',
  'Consecutive Characters',
  'Simplified Fractions',
  'Count Good Nodes in Binary Tree',
  'Form Largest Integer With Digits That Add up to Target',
  'Destination City',
  "Check If All 1's Are at Least Length K Places Away",
  'Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit',
  'Find the Kth Smallest Sum of a Matrix With Sorted Rows',
  'Build an Array With Stack Operations',
  'Count Triplets That Can Form Two Arrays of Equal XOR',
  'Minimum Time to Collect All Apples in a Tree',
  'Number of Ways of Cutting a Pizza',
  'Make Two Arrays Equal by Reversing Sub-arrays',
  'Check If a String Contains All Binary Codes of Size K',
  'Course Schedule IV',
  'Cherry Pickup II',
  'Number of Students Doing Homework at a Given Time',
  'Rearrange Words in a Sentence',
  'People Whose List of Favorite Companies Is Not a Subset of Another List',
  'Maximum Number of Darts Inside of a Circular Dartboard',
  'Check If a Word Occurs As a Prefix of Any Word in a Sentence',
  'Maximum Number of Vowels in a Substring of Given Length',
  'Pseudo-Palindromic Paths in a Binary Tree',
  'Max Dot Product of Two Subsequences',
  'Final Prices With a Special Discount in a Shop',
  'Allocate Mailboxes',
  'Subrectangle Queries',
  'Find Two Non-overlapping Sub-arrays Each With Target Sum',
  'Maximum Area of a Piece of Cake After Horizontal and Vertical Cuts',
  'Reorder Routes to Make All Paths Lead to the City Zero',
  'Probability of a Two Boxes Having The Same Number of Distinct Balls',
  'Shuffle the Array',
  'The k Strongest Values in an Array',
  'Design Browser History',
  'Paint House III',
  'Average Salary Excluding the Minimum and Maximum Salary',
  'The kth Factor of n',
  "Longest Subarray of 1's After Deleting One Element",
  'Parallel Courses II',
  'Running Sum of 1d Array',
  'Least Number of Unique Integers after K Removals',
  'Minimum Number of Days to Make m Bouquets',
  'XOR Operation in an Array',
  'Making File Names Unique',
  'Avoid Flood in The City',
  'Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree',
  'Range Sum of Sorted Subarray Sums',
  'Minimum Difference Between Largest and Smallest Value in Three Moves',
  'Stone Game IV',
  'Path Crossing',
  'Check If Array Pairs Are Divisible by k',
  'Number of Subsequences That Satisfy the Given Sum Condition',
  'Max Value of Equation',
  'Can Make Arithmetic Progression From Sequence',
  'Last Moment Before All Ants Fall Out of a Plank',
  'Count Submatrices With All Ones',
  'Minimum Possible Integer After at Most K Adjacent Swaps On Digits',
  'Count Odd Numbers in an Interval Range',
  'Number of Sub-arrays With Odd Sum',
  'Number of Good Ways to Split a String',
  'Minimum Number of Increments on Subarrays to Form a Target Array',
  'Number of Good Pairs',
  'Number of Substrings With Only 1s',
  'String Compression II',
  'Best Position for a Service Centre',
  'Water Bottles',
  'Number of Nodes in the Sub-Tree With the Same Label',
  'Maximum Number of Non-Overlapping Substrings',
  'Find a Value of a Mysterious Function Closest to Target',
  'Kth Missing Positive Number',
  'Can Convert String in K Moves',
  'Minimum Insertions to Balance a Parentheses String',
  'Maximum Number of Non-Overlapping Subarrays With Sum Equals Target',
  'Shuffle String',
  'Minimum Suffix Flips',
  'Number of Good Leaf Nodes Pairs',
  'Count Good Triplets',
  'Find the Winner of an Array Game',
  'Minimum Swaps to Arrange a Binary Grid',
  'Get the Maximum Score',
  'Thousand Separator',
  'Minimum Numbers of Function Calls to Make Target Array',
  'Detect Cycles in 2D Grid',
  'Make The String Great',
  'Find Kth Bit in Nth Binary String',
  'Find Longest Awesome Substring',
  'Minimum Cost to Cut a Stick',
  'Minimum Operations to Make Array Equal',
  'Magnetic Force Between Two Balls',
  'Minimum Number of Days to Eat N Oranges',
  'Matrix Diagonal Sum',
  'Number of Ways to Split a String',
  'Shortest Subarray to be Removed to Make Array Sorted',
  'Count All Possible Routes',
  'Most Visited Sector in  a Circular Track',
  'Maximum Number of Coins You Can Get',
  'Find Latest Group of Size M',
  'Stone Game V',
  'Detect Pattern of Length M Repeated K or More Times',
  'Maximum Length of Subarray With Positive Product',
  'Minimum Number of Days to Disconnect Island',
  'Number of Ways to Reorder Array to Get Same BST',
  'Sum of All Odd Length Subarrays',
  'Make Sum Divisible by P',
  'Maximum Sum Obtained of Any Permutation',
  'Strange Printer II',
  "Replace All ?'s to Avoid Consecutive Repeating Characters",
  'Number of Ways Where Square of Number Is Equal to Product of Two Numbers',
  'Minimum Time to Make Rope Colorful',
  'Special Positions in a Binary Matrix',
  'Count Unhappy Friends',
  'Min Cost to Connect All Points',
  'Check If String Is Transformable With Substring Sort Operations',
  'Alert Using Same Key-Card Three or More Times in a One Hour Period',
  'Find Servers That Handled Most Number of Requests',
  'Find Valid Matrix Given Row and Column Sums',
  'Rearrange Spaces Between Words',
  'Split a String Into the Max Number of Unique Substrings',
  'Maximum Non Negative Product in a Matrix',
  'Minimum Cost to Connect Two Groups of Points',
  'Crawler Log Folder',
  'Maximum Profit of Operating a Centennial Wheel',
  'Throne Inheritance',
  'Maximum Number of Achievable Transfer Requests',
  'Number of Sets of K Non-Overlapping Line Segments',
  'Coordinate With Maximum Network Quality',
  'Cat and Mouse II',
  'Fancy Sequence',
  'Special Array With X Elements Greater Than or Equal X',
  'Even Odd Tree',
  'Minimum One Bit Operations to Make Integers Zero',
  'Maximum Number of Visible Points',
  'Maximum Nesting Depth of the Parentheses',
  'Split Two Strings to Make Palindrome',
  'Count Subtrees With Max Distance Between Cities',
  'Sort Array by Increasing Frequency',
  'Widest Vertical Area Between Two Points Containing No Points',
  'Count Substrings That Differ by One Character',
  'Number of Ways to Form a Target String Given a Dictionary',
  'Largest Substring Between Two Equal Characters',
  'Lexicographically Smallest String After Applying Operations',
  'Best Team With No Conflicts',
  'Slowest Key',
  'Arithmetic Subarrays',
  'Path With Minimum Effort',
  'Defuse the Bomb',
  'Minimum Deletions to Make String Balanced',
  'Minimum Jumps to Reach Home',
  'Distribute Repeating Integers',
  'Check Array Formation Through Concatenation',
  'Count Sorted Vowel Strings',
  'Furthest Building You Can Reach',
  'Maximum Repeating Substring',
  'Minimum Number of Removals to Make Mountain Array',
  'Design Front Middle Back Queue',
  'Get Maximum in Generated Array',
  'Minimum Deletions to Make Character Frequencies Unique',
  'Sell Diminishing-Valued Colored Balls',
  'Create Sorted Array through Instructions',
  'Design an Ordered Stream',
  'Minimum Operations to Reduce X to Zero',
  'Determine if Two Strings Are Close',
  'Maximize Grid Happiness',
  'Check If Two String Arrays are Equivalent',
  'Smallest String With A Given Numeric Value',
  'Ways to Make a Fair Array',
  'Minimum Initial Energy to Finish Tasks',
  'Count the Number of Consistent Strings',
  'Sum of Absolute Differences in a Sorted Array',
  'Stone Game VI',
  'Delivering Boxes from Storage to Ports',
  'Richest Customer Wealth',
  'Find the Most Competitive Subsequence',
  'Minimum Moves to Make Array Complementary',
  'Minimize Deviation in Array',
  'Goal Parser Interpretation',
  'Max Number of K-Sum Pairs',
  'Minimum Incompatibility',
  'Concatenation of Consecutive Binary Numbers',
  'Number of Students Unable to Eat Lunch',
  'Average Waiting Time',
  'Maximum Binary String After Change',
  'Minimum Adjacent Swaps for K Consecutive Ones',
  'Count of Matches in Tournament',
  'Partitioning Into Minimum Number Of Deci-Binary Numbers',
  'Stone Game VII',
  'Reformat Phone Number',
  'Maximum Erasure Value',
  'Jump Game VI',
  'Checking Existence of Edge Length Limited Paths',
  'Calculate Money in Leetcode Bank',
  'Maximum Score From Removing Substrings',
  'Construct the Lexicographically Largest Valid Sequence',
  'Determine if String Halves Are Alike',
  'Maximum Number of Eaten Apples',
  'Find Minimum Time to Finish All Jobs',
  'Maximum XOR With an Element From Array',
  'Maximum Units on a Truck',
  'Count Good Meals',
  'Ways to Split Array Into Three Subarrays',
  'Minimum Operations to Make a Subsequence',
  'Find the Highest Altitude',
  'Minimum Number of People to Teach',
  'Decode XORed Permutation',
  'Count Ways to Make Array With Product',
  'Decode XORed Array',
  'Minimize Hamming Distance After Swap Operations',
  'Number Of Rectangles That Can Form The Largest Square',
  'Maximum Number of Balls in a Box',
  'Largest Submatrix With Rearrangements',
  'Sum of Unique Elements',
  'Maximum Absolute Sum of Any Subarray',
  'Minimum Length of String After Deleting Similar Ends',
  'Maximum Number of Events That Can Be Attended II',
  'Latest Time by Replacing Hidden Digits',
  'Change Minimum Characters to Satisfy One of Three Conditions',
  'Find Kth Largest XOR Coordinate Value',
  'Building Boxes',
  'Restore the Array From Adjacent Pairs',
  'Palindrome Partitioning IV',
  'Can You Eat Your Favorite Candy on Your Favorite Day?',
  'Longest Nice Substring',
  'Form Array by Concatenating Subarrays of Another Array',
  'Tree of Coprimes',
  'Map of Highest Peak',
  'Check if Array Is Sorted and Rotated',
  'Maximum Score From Removing Stones',
  'Largest Merge Of Two Strings',
  'Closest Subsequence Sum',
  'Minimum Changes To Make Alternating Binary String',
  'Count Number of Homogenous Substrings',
  'Minimum Limit of Balls in a Bag',
  'Find Nearest Point That Has the Same X or Y Coordinate',
  'Check if Number is a Sum of Powers of Three',
  'Sum of Beauty of All Substrings',
  'Count Pairs Of Nodes',
  'Merge Strings Alternately',
  'Minimum Number of Operations to Move All Balls to Each Box',
  'Maximum Score from Performing Multiplication Operations',
  'Maximize Palindrome Length From Subsequences',
  'Count Items Matching a Rule',
  'Closest Dessert Cost',
  'Equal Sum Arrays With Minimum Number of Operations',
  'Car Fleet II',
  'Second Largest Digit in a String',
  'Design Authentication Manager',
  'Maximize Score After N Operations',
  'Count Pairs With XOR in a Range',
  'Check if Binary String Has at Most One Segment of Ones',
  'Minimum Elements to Add to Form a Given Sum',
  'Number of Restricted Paths From First to Last Node',
  'Make the XOR of All Segments Equal to Zero',
  'Check if One String Swap Can Make Strings Equal',
  'Maximum Average Pass Ratio',
  'Maximum Score of a Good Subarray',
  'Determine Color of a Chessboard Square',
  'Sentence Similarity III',
  'Maximum Number of Groups Getting Fresh Donuts',
  'Count Nice Pairs in an Array',
  'Maximum Ascending Subarray Sum',
  'Number of Orders in the Backlog',
  'Maximum Value at a Given Index in a Bounded Array',
  'Maximum Number of Consecutive Values You Can Make',
  'Number of Different Integers in a String',
  'Evaluate the Bracket Pairs of a String',
  'Minimum Number of Operations to Reinitialize a Permutation',
  'Maximize Number of Nice Divisors',
  'Minimum Operations to Make the Array Increasing',
  'Queries on Number of Points Inside a Circle',
  'Maximum XOR for Each Query',
  'Minimum Number of Operations to Make String Sorted',
  'Truncate Sentence',
  'Finding the Users Active Minutes',
  'Minimum Absolute Sum Difference',
  'Number of Different Subsequences GCDs',
  'Sign of the Product of an Array',
  'Find the Winner of the Circular Game',
  'Minimum Sideway Jumps',
  'Replace All Digits with Characters',
  'Maximum Element After Decreasing and Rearranging',
  'Closest Room',
  'Check if the Sentence Is Pangram',
  'Maximum Ice Cream Bars',
  'Single-Threaded CPU',
  'Find XOR Sum of All Pairs Bitwise AND',
  'Sum of Digits in Base K',
  'Frequency of the Most Frequent Element',
  'Longest Substring Of All Vowels in Order',
  'Maximum Building Height',
  'Sorting the Sentence',
  'Rotating the Box',
  'Minimum Distance to the Target Element',
  'Splitting a String Into Descending Consecutive Values',
  'Minimum Interval to Include Each Query',
  'Minimum Adjacent Swaps to Reach the Kth Smallest Number',
  'Maximum Population Year',
  'Maximum Distance Between a Pair of Values',
  'Maximum Subarray Min-Product',
  'Largest Color Value in a Directed Graph',
  'Substrings of Size Three with Distinct Characters',
  'Minimize Maximum Pair Sum in Array',
  'Minimum XOR Sum of Two Arrays',
  'Get Biggest Three Rhombus Sums in a Grid',
  'Sum of All Subset XOR Totals',
  'Minimum Number of Swaps to Make the Binary String Alternating',
  'Finding Pairs With a Certain Sum',
  'Number of Ways to Rearrange Sticks With K Sticks Visible',
  'Longer Contiguous Segments of Ones than Zeros',
  'Minimum Speed to Arrive on Time',
  'Jump Game VII',
  'Stone Game VIII',
  'Check if All the Integers in a Range Are Covered',
  'Find the Student that Will Replace the Chalk',
  'Minimum Cost to Change the Final Value of Expression',
  'Check if Word Equals Summation of Two Words',
  'Maximum Value after Insertion',
  'Process Tasks Using Servers',
  'Minimum Skips to Arrive at Meeting On Time',
  'Determine Whether Matrix Can Be Obtained By Rotation',
  'Reduction Operations to Make the Array Elements Equal',
  'Minimum Number of Flips to Make the Binary String Alternating',
  'Minimum Space Wasted From Packaging',
  'Remove One Element to Make the Array Strictly Increasing',
  'Remove All Occurrences of a Substring',
  'Maximum Alternating Subsequence Sum',
  'Design Movie Rental System',
  'Redistribute Characters to Make All Strings Equal',
  'Merge Triplets to Form Target Triplet',
  'Maximum Number of Removable Characters',
  'The Earliest and Latest Rounds Where Players Compete',
  'Egg Drop With 2 Eggs and N Floors',
  'Largest Odd Number in String',
  'The Number of Full Rounds You Have Played',
  'Minimum Absolute Difference Queries',
  'Count Sub Islands',
  'Count Square Sum Triples',
  'Nearest Exit from Entrance in Maze',
  'Sum Game',
  'Minimum Cost to Reach Destination in Time',
  'Maximum Product Difference Between Two Pairs',
  'Cyclically Rotating a Grid',
  'Number of Wonderful Substrings',
  'Find a Peak Element II',
  'Build Array from Permutation',
  'Eliminate Maximum Number of Monsters',
  'Count Good Numbers',
  'Longest Common Subpath',
  'Check if All Characters Have Equal Number of Occurrences',
  'The Number of the Smallest Unoccupied Chair',
  'Describe the Painting',
  'Concatenation of Array',
  'Unique Length-3 Palindromic Subsequences',
  'Merge BSTs to Create Single BST',
  'Painting a Grid With Three Different Colors',
  'Add Minimum Number of Rungs',
  'Maximum Number of Points with Cost',
  'Maximum Genetic Difference Query',
  'Sum of Digits of String After Convert',
  'Largest Number After Mutating Substring',
  'Maximum Compatibility Score Sum',
  'Delete Duplicate Folders in System',
  'Check if Move is Legal',
  'Minimum Total Space Wasted With K Resizing Operations',
  'Three Divisors',
  'Maximum Number of Weeks for Which You Can Work',
  'Array With Elements Not Equal to Average of Neighbors',
  'Count Number of Special Subsequences',
  'Minimum Time to Type Word Using Special Typewriter',
  'Maximum Matrix Sum',
  'Number of Ways to Arrive at Destination',
  'Number of Ways to Separate Numbers',
  'Check If String Is a Prefix of Array',
  'Remove Stones to Minimize the Total',
  'Minimum Number of Swaps to Make the String Balanced',
  'Find the Longest Valid Obstacle Course at Each Position',
  'Number of Strings That Appear as Substrings in Word',
  'Minimum Non-Zero Product of the Array Elements',
  'Last Day Where You Can Still Cross',
  'Find the Middle Index in Array',
  'Find All Groups of Farmland',
  'Operations on Tree',
  'The Number of Good Subsets',
  'Find Greatest Common Divisor of Array',
  'Find Unique Binary String',
  'Minimize the Difference Between Target and Chosen Elements',
  'Find Array Given Subset Sums',
  'Minimum Difference Between Highest and Lowest of K Scores',
  'Find the Kth Largest Integer in the Array',
  'Minimum Number of Work Sessions to Finish the Tasks',
  'Number of Unique Good Subsequences',
  'Count Number of Pairs With Absolute Difference K',
  'Find Original Array From Doubled Array',
  'Maximum Earnings From Taxi',
  'Minimum Number of Operations to Make Array Continuous',
  'Find if Path Exists in Graph',
  'Count Special Quadruplets',
  'The Number of Weak Characters in the Game',
  'First Day Where You Have Been in All the Rooms',
  'GCD Sort of an Array',
  'Reverse Prefix of Word',
  'Number of Pairs of Interchangeable Rectangles',
  'Maximum Product of the Length of Two Palindromic Subsequences',
  'Smallest Missing Genetic Value in Each Subtree',
  'Convert 1D Array Into 2D Array',
  'Number of Pairs of Strings With Concatenation Equal to Target',
  'Maximize the Confusion of an Exam',
  'Maximum Number of Ways to Partition an Array',
  'Final Value of Variable After Performing Operations',
  'Sum of Beauty in the Array',
  'Detect Squares',
  'Longest Subsequence Repeated k Times',
  'Maximum Difference Between Increasing Elements',
  'Grid Game',
  'Check if Word Can Be Placed In Crossword',
  'The Score of Students Solving Math Expression',
  'Minimum Number of Moves to Seat Everyone',
  'Remove Colored Pieces if Both Neighbors are the Same Color',
  'The Time When the Network Becomes Idle',
  'Minimum Moves to Convert String',
  'Find Missing Observations',
  'Stone Game IX',
  'Smallest K-Length Subsequence With Occurrences of a Letter',
  'Minimum Operations to Make a Uni-Value Grid',
  'Stock Price Fluctuation ',
  'Partition Array Into Two Arrays to Minimize Sum Difference',
  'Kth Distinct String in an Array',
  'Two Best Non-Overlapping Events',
  'Plates Between Candles',
  'Number of Valid Move Combinations On Chessboard',
  'Check if Numbers Are Ascending in a Sentence',
  'Simple Bank System',
  'Count Number of Maximum Bitwise-OR Subsets',
  'Second Minimum Time to Reach Destination',
  'Number of Valid Words in a Sentence',
  'Next Greater Numerically Balanced Number',
  'Count Nodes With the Highest Score',
  'Parallel Courses III',
  'Check Whether Two Strings are Almost Equivalent',
  'Most Beautiful Item for Each Query',
  'Maximum Number of Tasks You Can Assign',
  'Smallest Index With Equal Value',
  'Minimum Operations to Convert Number',
  'Check if an Original String Exists Given Two Encoded Strings',
  'Count Vowel Substrings of a String',
  'Vowels of All Substrings',
  'Minimized Maximum of Products Distributed to Any Store',
  'Maximum Path Quality of a Graph',
  'Count Common Words With One Occurrence',
  'Minimum Number of Buckets Required to Collect Rainwater from Houses',
  'Minimum Cost Homecoming of a Robot in a Grid',
  'Count Fertile Pyramids in a Land',
  'Time Needed to Buy Tickets',
  'Decode the Slanted Ciphertext',
  'Two Furthest Houses With Different Colors',
  'Stamping the Grid',
  'Valid Arrangement of Pairs',
  'Sum of k-Mirror Numbers',
  'Find Subsequence of Length K With the Largest Sum',
  'Find Good Days to Rob the Bank',
  'Detonate the Maximum Bombs',
  'Find Target Indices After Sorting Array',
  'K Radius Subarray Averages',
  'Removing Minimum and Maximum From Array',
  'Find All People With Secret',
  'Finding 3-Digit Even Numbers',
  'Step-By-Step Directions From a Binary Tree Node to Another',
  'Maximum Number of Words Found in Sentences',
  'Find All Possible Recipes from Given Supplies',
  'Check if a Parentheses String Can Be Valid',
  'Abbreviating the Product of a Range',
  'Rings and Rods',
  'Sum of Subarray Ranges',
  'Watering Plants II',
  'Maximum Fruits Harvested After at Most K Steps',
  'Find First Palindromic String in the Array',
  'Adding Spaces to a String',
  'Number of Smooth Descent Periods of a Stock',
  'Minimum Operations to Make the Array K-Increasing',
  'Capitalize the Title',
  'Longest Palindrome by Concatenating Two Letter Words',
  'A Number After a Double Reversal',
  'Execution of All Suffix Instructions Staying in a Grid',
  'Intervals Between Identical Elements',
  'Recover the Original Array',
  "Check if All A's Appears Before All B's",
  'Number of Laser Beams in a Bank',
  'Destroying Asteroids',
  'Maximum Employees to Be Invited to a Meeting',
  'Minimum Cost of Buying Candies With Discount',
  'Count the Hidden Sequences',
  'K Highest Ranked Items Within a Price Range',
  'Number of Ways to Divide a Long Corridor',
  'Check if Every Row and Column Contains All Numbers',
  "Minimum Swaps to Group All 1's Together II",
  'Count Words Obtained After Adding a Letter',
  'Earliest Possible Day of Full Bloom',
  'Divide a String Into Groups of Size k',
  'All Divisions With the Highest Score of a Binary Array',
  'Solving Questions With Brainpower',
  'Maximum Running Time of N Computers',
  'Minimum Sum of Four Digit Number After Splitting Digits',
  'Partition Array According to Given Pivot',
  'Minimum Cost to Set Cooking Time',
  'Minimum Difference in Sums After Removal of Elements',
  'Count Elements With Strictly Smaller and Greater Elements ',
  'Find All Lonely Numbers in the Array',
  'Rearrange Array Elements by Sign',
  'Maximum Good People Based on Statements',
  'Keep Multiplying Found Values by Two',
  'Find Substring With Given Hash Value',
  'Groups of Strings',
  'Find Three Consecutive Integers That Sum to a Given Number',
  'Maximum Split of Positive Even Integers',
  'Count Good Triplets in an Array',
  'Sort Even and Odd Indices Independently',
  'Smallest Value of the Rearranged Number',
  'Design Bitset',
  'Minimum Time to Remove All Cars Containing Illegal Goods',
  'Count Operations to Obtain Zero',
  'Minimum Operations to Make the Array Alternating',
  'Removing Minimum Number of Magic Beans',
  'Maximum AND Sum of Array',
  'Counting Words With a Given Prefix',
  'Minimum Number of Steps to Make Two Strings Anagram II',
  'Minimum Time to Complete Trips',
  'Minimum Time to Finish the Race',
  'Count Integers With Even Digit Sum',
  'Construct String With Repeat Limit',
  'Count Array Pairs Divisible by K',
  'Cells in a Range on an Excel Sheet',
  'Append K Integers With Minimal Sum',
  'Create Binary Tree From Descriptions',
  'Replace Non-Coprime Numbers in Array',
  'Divide Array Into Equal Pairs',
  'Maximize Number of Subsequences in a String',
  'Minimum Operations to Halve Array Sum',
  'Minimum White Tiles After Covering With Carpets',
  'Most Frequent Number Following Key In an Array',
  'Count Hills and Valleys in an Array',
  'Count Collisions on a Road',
  'Maximum Points in an Archery Competition',
  'Longest Substring of One Repeating Character',
  'Find All K-Distant Indices in an Array',
  'Find Triangular Sum of an Array',
  'Number of Ways to Select Buildings',
  'Sum of Scores of Built Strings',
  'Largest Number After Digit Swaps by Parity',
  'Minimize Result by Adding Parentheses to Expression',
  'Maximum Product After K Increments',
  'Maximum Total Beauty of the Gardens',
  'Minimum Number of Operations to Convert Time',
];
